project:
  type: website

website:
  title: "Maddie Mann"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: cover-letter.qmd
        text: Cover Letter
      - href: analysis2.qmd
        text: Sample Analysis
      

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true


