---
title: "Prostate Cancer Progression Free Survival and Genomic Alteration Analysis"
format:
  html:
    theme: cosmo
    toc: true
    code-fold: false
execute:
  warning: false
  message: false
---



# Introduction

This analysis investigates whether genomic and clinical variables can predict prostate cancer progression free survival status using machine learning classification models. Additional regression analysis explores which biological variables may influence Fraction of Genome Altered, a measure of genomic instability commonly associated with tumor progression.

The analysis includes:

* Data cleaning and preprocessing
* Classification modeling for survival prediction
* Feature importance analysis
* ROC curve evaluation
* Confusion matrix visualization
* Regression analysis for genomic instability of tumor microenviroments. 

# Import Packages
```{python}

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import KFold, GridSearchCV, StratifiedKFold

from sklearn.metrics import (classification_report, confusion_matrix, roc_curve, roc_auc_score, r2_score)
```

# Load Data

```{python}

prostate_cancer = pd.read_csv(
    "data/prad_tcga_pan_can_atlas_2018_clinical_data.tsv",
    sep='\t'
)
```

# Data Cleaning

```{python}

prostate_cancer.columns = prostate_cancer.columns.str.replace(' ', '_')
prostate_cancer.columns = prostate_cancer.columns.str.replace(r'[\(\)]', '', regex=True)
```

#### Non-Predictive Columns 
Remove columns that have all/majority 'NA' values, near zero variance, and identifier variables. 
```{python}

non_predictor = [
    'Study_ID', 'Patient_ID', 'Sample_ID', 'Patient_Weight', 'Cancer_Type', 'Cancer_Type_Detailed',
    'Sex', 'Number_of_Samples_Per_Patient', 'American_Joint_Committee_on_Cancer_Metastasis_Stage_Code', 
                'Primary_Lymph_Node_Presentation_Assessment', 'Neoplasm_Disease_Stage_American_Joint_Committee_on_Cancer_Code', 
                'American_Joint_Committee_on_Cancer_Publication_Version_Type', 
                'Neoplasm_Disease_Stage_American_Joint_Committee_on_Cancer_Code', 'TCGA_PanCanAtlas_Cancer_Type_Acronym',
                'Last_Alive_Less_Initial_Pathologic_Diagnosis_Date_Calculated_Day_Value', 'Disease-specific_Survival_status',
                'Ethnicity_Category', 'Neoplasm_Histologic_Grade', 'Neoadjuvant_Therapy_Type_Administered_Prior_To_Resection_Text', 'ICD-10_Classification', 'International_Classification_of_Diseases_for_Oncology,_Third_Edition_ICD-O-3_Histology_Code',
                'International_Classification_of_Diseases_for_Oncology,_Third_Edition_ICD-O-3_Site_Code', 
                'Informed_consent_verified', 'Oncotree_Code', 'Other_Patient_ID',
                'American_Joint_Committee_on_Cancer_Metastasis_Stage_Code', 'Primary_Lymph_Node_Presentation_Assessment', 
                'Race_Category', 'Number_of_Samples_Per_Patient', 'Sample_Type',
                'Somatic_Status', 'Subtype', 'Tissue_Source_Site', 'Tissue_Prospective_Collection_Indicator',
       'Tissue_Retrospective_Collection_Indicator', 'Tissue_Source_Site_Code', 'Tumor_Disease_Anatomic_Site','Last_Communication_Contact_from_Initial_Pathologic_Diagnosis_Date', 'Birth_from_Initial_Pathologic_Diagnosis_Date',
       'Form_completion_date'
]

prostate_cancer = prostate_cancer.drop(columns=non_predictor)

```

```{python}
prostate_cancer = prostate_cancer.rename(columns={
    'Neoplasm_Disease_Lymph_Node_Stage_American_Joint_Committee_on_Cancer_Code': 'Lymph_Node_Stage',
    'American_Joint_Committee_on_Cancer_Tumor_Stage_Code': 'Tumor_Stage'
})
```

# Remove Other Potential Targets 

These variables are highly correlated with the predictor.  
```{python}
other_target = [
    'Disease_Free_Months',
    'Disease_Free_Status',
    'Progress_Free_Survival_Months',
    'Months_of_disease-specific_survival',
    'Overall_Survival_Months',
    'Overall_Survival_Status',
    'Person_Neoplasm_Cancer_Status',
    'New_Neoplasm_Event_Post_Initial_Therapy_Indicator',
]

prostate_class = prostate_cancer.drop(columns=other_target)
```

```{python}
prostate_class['Progression_Free_Status'] = (prostate_class['Progression_Free_Status'].astype(str).str[0].astype(int))
```

# Exploratory Analysis

## Distribution of Progression-Free Survival Status

```{python}
plt.figure(figsize=(6,4))

sns.countplot(x=prostate_class['Progression_Free_Status'])

plt.xlabel('Progression-Free Status')
plt.ylabel('Count')
plt.title('Distribution of Survival Classes')

plt.tight_layout()
plt.show()
```

There is a large class imbalance. 

## Distribution of Fraction of Genome Altered

```{python}
plt.figure(figsize=(7,5))

plt.hist(prostate_cancer['Fraction_Genome_Altered'].dropna(), bins=30)

plt.xlabel('Fraction of Genome Altered')
plt.ylabel('Count')
plt.title('Distribution of Fraction of Genome Altered')

plt.tight_layout()
plt.show()
```

# Train-Test Split

```{python}

X = prostate_class.drop(columns='Progression_Free_Status')
y = prostate_class['Progression_Free_Status']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    train_size=0.7,
    random_state=4025,
    stratify=y
)
```

# Preprocessing

```{python}
numeric_cols = ['Diagnosis_Age', 'Aneuploidy_Score', 'Buffa_Hypoxia_Score', 'Fraction_Genome_Altered', 'MSI_MANTIS_Score', 'MSIsensor_Score', 'Mutation_Count', 'Ragnum_Hypoxia_Score', 'Tumor_Break_Load', 'TMB_nonsynonymous', 'Winter_Hypoxia_Score']
categorical_cols = ['Genetic_Ancestry_Label', 'In_PanCan_Pathway_Analysis', 'Lymph_Node_Stage', 'Tumor_Stage', 'Prior_Diagnosis', 'Radiation_Therapy', 'Tumor_Type']
```

```{python}

numeric_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='median'))
])

categorical_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])
```

```{python}

preprocessor = ColumnTransformer([
    ('num', numeric_transformer, numeric_cols),
    ('cat', categorical_transformer, categorical_cols)
])
```

# Classification Model

```{python}

rf_classifier = RandomForestClassifier(
    n_estimators=100,
    max_depth=6,
    class_weight='balanced',
    random_state=4025
)

rf_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('rf', rf_classifier)
])

rf_pipeline.fit(X_train, y_train)
```

# Random Forest Evaluation

## Classification Report

```{python}
y_pred = rf_pipeline.predict(X_test)

print(classification_report(y_test, y_pred))
```

# Cross Validation 
```{python}
cv = StratifiedKFold(n_splits = 10, shuffle = True, random_state=4025)

param_grid = {
    'rf__n_estimators': [100, 200, 300],
    'rf__max_depth': [4, 6, 8, 10],
    'rf__min_samples_split': [2, 5, 10],
    'rf__min_samples_leaf': [1, 2, 4]
}

rf_grid = GridSearchCV(
    estimator=rf_pipeline,
    param_grid=param_grid,
    cv=cv,
    scoring='f1', 
    n_jobs=-1,
)

rf_grid.fit(X_train, y_train)

y_pred_rf = rf_grid.predict(X_test)

print(rf_grid.best_params_)
print(rf_grid.best_score_)

```

### CV Classification Report 

```{python}
print(classification_report(y_test, y_pred_rf))
```

F1 score was used for scoring cross validation. Class imbalnce leads to high accuracy baseline. 

## Confusion Matrix

0 (negative) class is progressing without return of cancer. 
1 (positive)class is progressing and then cancer returns. 

```{python}
cm = confusion_matrix(y_test, y_pred_rf)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    cbar=False
)

plt.xticks(
    [0.5, 1.5],
    ['Predicted Negative', 'Predicted Positive']
)

plt.yticks(
    [0.5, 1.5],
    ['Actual Negative', 'Actual Positive'],
    rotation=0
)

plt.xlabel('Predicted Outcome')
plt.ylabel('True Outcome')
plt.title('Confusion Matrix: Survival Classification')

plt.tight_layout()
plt.show()

```


## ROC Curve

```{python}
y_probs = rf_grid.predict_proba(X_test)[:, 1]

fpr, tpr, thresholds = roc_curve(y_test, y_probs)
auc_score = roc_auc_score(y_test, y_probs)

plt.figure(figsize=(6,6))

plt.plot(fpr, tpr, label=f'AUC = {auc_score:.3f}')
plt.plot([0, 1], [0, 1], linestyle='--')

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve: Survival Prediction Model')
plt.legend()

plt.tight_layout()
plt.show()
```

# Feature Importance Analysis

```{python}

importances = rf_pipeline.named_steps['rf'].feature_importances_
feature_names = rf_pipeline.named_steps['preprocessor'].get_feature_names_out()

rf_importance_df = pd.Series(
    importances,
    index=feature_names
).sort_values(ascending=False)

rf_importance_df.head(10)
```

## Top Predictive Variables

```{python}

top_features = rf_importance_df.head(10)

fig, ax = plt.subplots(figsize=(9,5))

ax.barh(
    top_features.index[::-1],
    top_features.values[::-1]
)

ax.set_xlabel('Feature Importance')
ax.set_title('Top 10 Predictive Features')

ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.tight_layout()
plt.show()
```

# Regression Analysis: Fraction of Genome Altered
Since fraction of genome altered was the most important feature in determining progression free status looking at what features impact the genome can be beneficial. 

```{python}

plt.figure(figsize=(7,5))

plt.scatter(
    prostate_cancer['Ragnum_Hypoxia_Score'],
    prostate_cancer['Fraction_Genome_Altered']
)

plt.xlabel('Hypoxia Score')
plt.ylabel('Fraction of Genome Altered')
plt.title('Hypoxia and Genomic Instability')

plt.tight_layout()
plt.show()
```

```{python}

prostate_reg = prostate_class.dropna(subset=['Fraction_Genome_Altered'])

X_expanded = prostate_reg[[
    'Ragnum_Hypoxia_Score', 
    'Buffa_Hypoxia_Score', 
    'MSI_MANTIS_Score', 
    'Mutation_Count',       
    'Diagnosis_Age'         
]]

num_vars = [
    'Ragnum_Hypoxia_Score', 
    'Buffa_Hypoxia_Score', 
    'MSI_MANTIS_Score', 
    'Mutation_Count',       
    'Diagnosis_Age'         
]

y = prostate_reg['Fraction_Genome_Altered']

X_train, X_test, y_train, y_test = train_test_split(
    X_expanded, y,
    train_size=0.7,
    random_state=4025
)

numeric_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='median'))
])



preprocessor = ColumnTransformer([
    ('num', numeric_transformer, num_vars)
])

reg_tree_pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('tree', DecisionTreeRegressor(random_state=4025, ccp_alpha=0.0001))
])

reg_tree_pipe.fit(X_train, y_train)


print(f"Train R^2: {reg_tree_pipe.score(X_train, y_train):.3f}")
print(f"Test R^2: {reg_tree_pipe.score(X_test, y_test):.3f}")

```

```{python}

cv = KFold(n_splits=10, shuffle=True, random_state=4025)



param_grid = {
    'tree__max_depth': [3, 5, 10, None],
    'tree__min_samples_split': [2, 5, 10],
    'tree__min_samples_leaf': [1, 2, 4]
}

tree_grid = GridSearchCV(
    estimator=reg_tree_pipe,
    param_grid=param_grid,
    cv=cv,
    scoring='r2'
)

tree_grid.fit(X_train, y_train)

```

```{python}
print("Best Parameters:")
print(tree_grid.best_params_)

print(f"\nBest Cross-Validation R²: {tree_grid.best_score_:.3f}")
best_tree = tree_grid.best_estimator_

```

## Regression Model Performance

```{python}
y_pred_reg = tree_grid.predict(X_test)
r2 = r2_score(y_test, y_pred_reg)

print(f"The best test tree R2 value is {r2}.")
```

```{python}
importances = best_tree.named_steps[
    'tree'
].feature_importances_

feature_names = best_tree.named_steps[
    'preprocessor'
].get_feature_names_out()

rf_reg_importance_df = pd.Series(
    importances,
    index=feature_names
).sort_values(ascending=False)

print(rf_reg_importance_df.head(5))
```

```{python}
top_features = rf_reg_importance_df.head(5)

fig, ax = plt.subplots(figsize=(6,5))

ax.barh(
    top_features.index[::-1],
    top_features.values[::-1]
)

ax.set_xlabel('Feature Importance')
ax.set_title(
    'Top Variables Influencing Fraction of Genome Altered'
)

ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.tight_layout()
plt.show()
```


# Discussion

This analysis explored whether genomic and clinical variables could predict prostate cancer progression-free survival status using machine learning classification models. A random forest classifier was trained using processed clinical and genomic variables following data cleaning and preprocessing.

The classification model demonstrated predictive capability for survival outcomes, and ROC curve analysis provided additional evaluation of model discrimination performance across classification thresholds. Feature importance analysis identified Fraction of Genome Altered as one of the strongest predictive variables, suggesting that genomic instability may contribute significantly to prostate cancer progression.

Additional exploratory analysis investigated relationships between hypoxia and Fraction of Genome Altered. Observed trends between these variables support the hypothesis that tumor microenvironment conditions may influence genomic instability and tumor progression.

Overall, this project demonstrates how machine learning approaches can be applied to cancer genomics data to investigate clinically relevant predictors of disease progression and survival outcomes.

# Future Directions

Potential future improvements include:

* Hyperparameter optimization
* Additional feature engineering 
    * Correct for class imbalance
    * Feature Selection 




